### ISSUE TITLE
Snapping lines to angles

### ISSUE THREAD

**Issue by DanielOaks** [conundrumer/lr#1]
It'd be pretty cool to be able to hold down Shift or something while drawing a line, and have it snap to angles (45/30/etc). Maybe even a little textbox down the bottom-right that lets you type in the degree you want to snap to?

I'd have a look at this, but I'm completely new to JS projects, have no idea where this sorta thing would hook in. Thanks for the awesome project though, excited to see where it goes!

**Comment by conundrumer** [comment]
Hey there, wow how did you come across this project? I'm still in the midst of implementing basic features and organizing everything, so I haven't prioritized documentation.

Angle snapping is actually already implemented and being actively used in a modded version of the original Line Rider, so it's something I do intend to support, though most likely only at 15 degree increments. Line Rider is partially a vector graphics editor, but it shouldn't be a complete one.

The shift key is currently being used to flip lines, so you'd have to attach angle snapping to ctrl/cmd, which means fully implementing modifier key support. I've only detected the shift key because combinations of mod keys are somewhat tricky to handle.

**Comment by DanielOaks** [comment]
Ah right, I forgot about Shift being used for that. That makes sense.

I remembered back to when I'd spend lots of time making Line Rider tracks.
Decided to take a look around and see whether Canvas Rider or a clone had
made it onto Github. Was pleasantly surprised to find this project! :)

I managed to get it up and running locally. I've just never worked with
Javascript server-side so I'm not as familiar with the layout of JS
projects. Will definitely keep an eye on the project, but I'm probably
gonna be more just an occasional tester than a proper contributor.

**Comment by conundrumer** [comment]
Somewhat unrelated: If you're interested, you can check out the remaining [Line Rider community](http://iridethelines.forumotion.com/)

**Comment by conundrumer** [comment]
implemented by 238f07d8301c8869ec24e71b22966ee0b154e834

**Comment by DanielOaks** [comment]
Awesome, thanks for the quick response. That works really well, especially on the Mac since that maps to the command key.
